# Use root/example as user/password credentials
version: '3.1'

services:

  mongo-bit:
    image: bitnami/mongodb:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: 1o2XZgY1fPbJ

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#      ME_CONFIG_MONGODB_ADMINPASSWORD: 1o2XZgY1fPbJ